# Generated by Django 5.1.3 on 2024-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=4)),
                ('postalCode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=20)),
                ('iban', models.CharField(max_length=20)),
            ],
        ),
    ]
